# Generated by Django 4.2.3 on 2023-07-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PEN', 'pending'), ('ACC', 'accepted'), ('REJ', 'rejected')], default='New', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autumn', models.CharField(blank=True, max_length=12)),
                ('spring', models.CharField(blank=True, max_length=12)),
                ('summer', models.CharField(blank=True, max_length=12)),
                ('winter', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=28)),
                ('surname', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=28)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('email',), name='pereval_users_name_unique'),
        ),
        migrations.AddField(
            model_name='images',
            name='added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.added'),
        ),
        migrations.AddField(
            model_name='added',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords'),
        ),
        migrations.AddField(
            model_name='added',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level'),
        ),
        migrations.AddField(
            model_name='added',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users'),
        ),
    ]
